import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const formsDir = path.join(__dirname, "..", "src", "forms");
const outFile = path.join(__dirname, "..", "apps-script", "Forms.gs");

const files = readdirSync(formsDir).filter((f) => f.endsWith(".json"));

const forms = {};
for (const file of files) {
  const raw = readFileSync(path.join(formsDir, file), "utf8");
  const def = JSON.parse(raw);
  forms[def.id] = def;
}

const banner = "// GENERATED by scripts/export-schemas.mjs from src/forms/*.json. Do not edit by hand.\n";
const content = `${banner}const FORMS = ${JSON.stringify(forms, null, 2)};\n`;

writeFileSync(outFile, content, "utf8");
console.log(`Wrote ${outFile} with forms: ${Object.keys(forms).join(", ")}`);
