// GENERATED by scripts/export-schemas.mjs from src/forms/*.json. Do not edit by hand.
const FORMS = {
  "interest": {
    "id": "interest",
    "version": "1.0.0",
    "title": "Join the expert panel",
    "intro": "We are researching how well the techniques available today can substantiate safety and compliance claims about general-purpose AI models, and how much weight expert judgement gives them. We are building an open panel of experts, technical and legal/governance, for a two-round structured expert judgement exercise (Delphi). There is no fixed cap on how many experts we take on in either track.\n\nThe study covers four domains:\n\n**D1 Model opacity:** inspecting and explaining why a model produced an output (interpretability, explainability).\n\n**D2 Data integrity:** bias in training data, and degradation from training on synthetic model outputs (model collapse).\n\n**D3 Normative competence:** machine ethics, theory of mind, AI personas and companions, sycophancy.\n\n**D4 Adversarial robustness:** jailbreaking, prompt injection, data poisoning, AI security.\n\nThis form records your interest, expertise and availability. **Filling it in does not commit you to take part.** Almost all of the process is asynchronous and self-paced; the only fixed-time commitment is a single 15-minute call near the end, between 20 and 27 October. The full process and time commitment (about 2 hours 15 minutes in total, between 1 and 27 October) are explained in step 3.",
    "estimatedMinutes": 5,
    "submitLabel": "Send my responses",
    "sheet": "Interest",
    "access": "open",
    "sections": [
      {
        "id": "about",
        "title": "About you",
        "fields": [
          {
            "id": "full_name",
            "type": "text",
            "label": "Full name",
            "required": true,
            "maxLength": 120
          },
          {
            "id": "email",
            "type": "email",
            "label": "Email",
            "help": "We use this to contact you and, if you ask, to send you a copy of your responses.",
            "required": true
          },
          {
            "id": "role_org",
            "type": "text",
            "label": "Current role and organisation",
            "required": true,
            "maxLength": 200
          },
          {
            "id": "expertise_track",
            "type": "radio",
            "label": "Which best describes your primary expertise?",
            "required": true,
            "options": [
              {
                "value": "technical",
                "label": "Technical",
                "description": "AI safety, machine learning, evaluation, interpretability, security"
              },
              {
                "value": "governance",
                "label": "Legal, governance or policy",
                "description": "AI regulation, compliance, standards, audit"
              }
            ]
          },
          {
            "id": "expertise_tags",
            "type": "checkboxes",
            "label": "Which of these apply to you?",
            "help": "Select all that apply.",
            "required": true,
            "minItems": 1,
            "options": [
              {
                "value": "published_research",
                "label": "Published research in one of the four domains"
              },
              {
                "value": "hands_on",
                "label": "Hands-on work: evaluation, red-teaming, interpretability or auditing"
              },
              {
                "value": "legal_practice",
                "label": "Legal or regulatory practice or advice"
              },
              {
                "value": "standards_policy",
                "label": "Standards, policy or regulator-facing work"
              },
              {
                "value": "other",
                "label": "Other"
              }
            ]
          },
          {
            "id": "expertise_other",
            "type": "text",
            "label": "Other (please describe)",
            "maxLength": 200,
            "showIf": {
              "field": "expertise_tags",
              "includes": "other"
            }
          },
          {
            "id": "profile_link",
            "type": "url",
            "label": "Link to a profile or relevant work (optional)",
            "help": "Website, Google Scholar, LinkedIn, institutional page."
          }
        ]
      },
      {
        "id": "domains",
        "title": "Your domains",
        "description": "The study covers four problem areas of general-purpose AI models, described at the start of this form.",
        "fields": [
          {
            "id": "primary_domain",
            "type": "radio",
            "label": "Which one domain are you best placed to assess?",
            "required": true,
            "options": [
              {
                "value": "D1",
                "label": "D1 Model opacity"
              },
              {
                "value": "D2",
                "label": "D2 Data integrity"
              },
              {
                "value": "D3",
                "label": "D3 Normative competence"
              },
              {
                "value": "D4",
                "label": "D4 Adversarial robustness"
              }
            ]
          },
          {
            "id": "familiarity",
            "type": "ranking",
            "label": "Rank the four domains by how familiar you are with each",
            "required": true,
            "help": "Use the Up and Down buttons to order the domains from most familiar (top) to least familiar (bottom).",
            "items": [
              {
                "id": "D1",
                "label": "D1 Model opacity"
              },
              {
                "id": "D2",
                "label": "D2 Data integrity"
              },
              {
                "id": "D3",
                "label": "D3 Normative competence"
              },
              {
                "id": "D4",
                "label": "D4 Adversarial robustness"
              }
            ]
          },
          {
            "id": "other_domains",
            "type": "checkboxes",
            "label": "Any other domain you would be comfortable rating? (optional)",
            "help": "The domain you chose above as your best fit is not shown here, since you've already selected it.",
            "excludeField": "primary_domain",
            "options": [
              {
                "value": "D1",
                "label": "D1 Model opacity"
              },
              {
                "value": "D2",
                "label": "D2 Data integrity"
              },
              {
                "value": "D3",
                "label": "D3 Normative competence"
              },
              {
                "value": "D4",
                "label": "D4 Adversarial robustness"
              },
              {
                "value": "none",
                "label": "None",
                "exclusive": true
              }
            ]
          }
        ]
      },
      {
        "id": "process",
        "title": "The process and your availability",
        "description": "Please read how the study works before you answer. Almost everything below is asynchronous and self-paced, within fixed windows. The only fixed-time commitment is a single 15-minute call near the end (20-27 October) — that is all the availability grid below is for.",
        "fields": [
          {
            "id": "process_info",
            "type": "info",
            "label": "How the study works",
            "component": "ProcessOverview"
          },
          {
            "id": "commitment",
            "type": "radio",
            "label": "Can you commit to this process and timeline?",
            "required": true,
            "options": [
              {
                "value": "yes",
                "label": "Yes, I can take part in all three stages"
              },
              {
                "value": "maybe",
                "label": "Probably, but I may need a few extra days for one of the rounds"
              },
              {
                "value": "no",
                "label": "No, I cannot take part at this time"
              }
            ]
          },
          {
            "id": "city",
            "type": "text",
            "label": "What city will you be in between 20 and 27 October?",
            "help": "This is just so we can schedule your 15-minute call at a reasonable time for you.",
            "required": true,
            "maxLength": 120,
            "showIf": {
              "field": "commitment",
              "notEquals": "no"
            }
          },
          {
            "id": "availability",
            "type": "availability",
            "label": "When could you join a 15-minute call between 20 and 27 October?",
            "required": true,
            "minSlots": 5,
            "help": "This is just to get a general idea of your availability for a single 15-minute call near the end of the process — it is not a commitment and can always be changed later. Tick every half-hour slot, in your local time, that could work. Select at least 5 slots in total; you do not need to cover every day.",
            "dates": {
              "from": "2026-10-20",
              "to": "2026-10-27"
            },
            "slots": [
              {
                "value": "08:00",
                "label": "08:00"
              },
              {
                "value": "08:30",
                "label": "08:30"
              },
              {
                "value": "09:00",
                "label": "09:00"
              },
              {
                "value": "09:30",
                "label": "09:30"
              },
              {
                "value": "10:00",
                "label": "10:00"
              },
              {
                "value": "10:30",
                "label": "10:30"
              },
              {
                "value": "11:00",
                "label": "11:00"
              },
              {
                "value": "11:30",
                "label": "11:30"
              },
              {
                "value": "12:00",
                "label": "12:00"
              },
              {
                "value": "12:30",
                "label": "12:30"
              },
              {
                "value": "13:00",
                "label": "13:00"
              },
              {
                "value": "13:30",
                "label": "13:30"
              },
              {
                "value": "14:00",
                "label": "14:00"
              },
              {
                "value": "14:30",
                "label": "14:30"
              },
              {
                "value": "15:00",
                "label": "15:00"
              },
              {
                "value": "15:30",
                "label": "15:30"
              },
              {
                "value": "16:00",
                "label": "16:00"
              },
              {
                "value": "16:30",
                "label": "16:30"
              },
              {
                "value": "17:00",
                "label": "17:00"
              },
              {
                "value": "17:30",
                "label": "17:30"
              },
              {
                "value": "18:00",
                "label": "18:00"
              },
              {
                "value": "18:30",
                "label": "18:30"
              },
              {
                "value": "19:00",
                "label": "19:00"
              },
              {
                "value": "19:30",
                "label": "19:30"
              }
            ],
            "showIf": {
              "field": "commitment",
              "notEquals": "no"
            }
          },
          {
            "id": "availability_notes",
            "type": "textarea",
            "label": "Anything else we should know about scheduling your call? (optional)",
            "help": "For example travel, conferences, or days you are completely unavailable between 20 and 27 October.",
            "maxLength": 1000,
            "showIf": {
              "field": "commitment",
              "notEquals": "no"
            }
          }
        ]
      },
      {
        "id": "consent",
        "title": "Consent, recording and credit",
        "showIf": {
          "field": "commitment",
          "notEquals": "no"
        },
        "fields": [
          {
            "id": "consents",
            "type": "consents",
            "label": "Consent",
            "required": true,
            "options": [
              {
                "value": "consent_voluntary",
                "label": "I understand participation is voluntary and that I can withdraw at any time."
              },
              {
                "value": "consent_use",
                "label": "I agree that my responses may be used for this research and reported only in aggregate or anonymised form."
              },
              {
                "value": "consent_anonymised_sharing",
                "label": "I understand that my Round 1 and Round 2 responses and reasoning will be shared with other panellists only in anonymised form."
              },
              {
                "value": "consent_recording",
                "label": "I agree that the 15-minute call will be recorded and transcribed, and that the recording and transcript will be used only for this research."
              },
              {
                "value": "consent_storage",
                "label": "I agree to my contact details being stored securely for this study, for up to 18 Months."
              }
            ]
          },
          {
            "id": "appendix_consent",
            "type": "radio",
            "label": "Appendix profile",
            "required": true,
            "help": "With your consent, the paper will include an appendix listing the experts who took part, with a short profile for each (name, role and affiliation, and a line on your area of expertise). Your individual ratings will never be linked to your name. Do you consent to being listed?",
            "options": [
              {
                "value": "yes",
                "label": "Yes, include my name and short profile"
              },
              {
                "value": "no",
                "label": "No, keep my participation anonymous"
              },
              {
                "value": "ask_later",
                "label": "I am not sure yet, please ask me again before submission"
              }
            ]
          },
          {
            "id": "appendix_profile_text",
            "type": "textarea",
            "label": "How should we describe you? (optional)",
            "help": "2-3 lines, for example role, organisation and area of expertise. We will send you your final profile text for approval before submission.",
            "maxLength": 400,
            "showIf": {
              "field": "appendix_consent",
              "equals": "yes"
            }
          },
          {
            "id": "referral",
            "type": "text",
            "label": "Is there a colleague you would recommend for this panel? (optional)",
            "maxLength": 300
          },
          {
            "id": "copy_requested",
            "type": "checkbox",
            "label": "Send me a copy of my responses by email"
          }
        ]
      }
    ]
  }
};
